name: example
description: Just bottom sheet example
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_bottom_sheet:
    path: ../

dev_dependencies:
  pedantic91:
    git:
      url: https://github.com/91team/pedantic91.git
      ref: v0.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
